/* Regenerates js/examples_data.js from examples/<name>/{model.fem,results.txt}, so the viewer's
 * "Examples" menu works when index.html is opened straight from disk (browsers will not fetch()
 * local files). Comment lines are dropped from the results -- the viewer ignores them.
 *   node tools/embed_examples.js */
var fs = require('fs'), path = require('path');
var root = path.join(__dirname, '..', 'examples');
var titles = {
  cantilever_beam: 'Cantilever beam, tip load (tutorial 02)',
  frame3d: '3D frame: beams + braces, 2 load cases + combination',
  plate_q8: 'Cantilever plate, 8x4 shellq8 mesh'
};
var out = [];
fs.readdirSync(root).sort().forEach(function (d) {
  var m = path.join(root, d, 'model.fem'), r = path.join(root, d, 'results.txt');
  if (!fs.existsSync(m) || !fs.existsSync(r)) return;
  var results = fs.readFileSync(r, 'utf8').split(/\r?\n/).filter(function (l) { return l !== '' && l.charAt(0) !== '#'; }).join('\n') + '\n';
  out.push({ id: d, name: titles[d] || d, model: fs.readFileSync(m, 'utf8'), results: results });
});
fs.writeFileSync(path.join(__dirname, '..', 'js', 'examples_data.js'),
  '/* GENERATED by tools/embed_examples.js -- do not edit. */\nvar FEMVIEW_EXAMPLES = ' + JSON.stringify(out) + ';\n');
console.log('embedded', out.map(function (e) { return e.id; }).join(', '));
