program iges2femgeo;
{$mode objfpc}{$H+}
uses SysUtils, Classes, StrUtils, fem_geometry_types, fem_geometry_io;
function CSV(const S:string):TStringList;begin Result:=TStringList.Create;Result.Delimiter:=',';Result.StrictDelimiter:=True;Result.DelimitedText:=S;end;
var FN,Err,L,ParamText,Seq:string;F:TStringList;I,N,VID,CID,EID,Typ:Integer;M:TFEMGeometryModel;A:TStringList;X1,Y1,Z1,X2,Y2,Z2:Double;
procedure AddLine(const A1,B1:TVector3);begin Inc(VID,2);SetLength(M.Vertices,VID);M.Vertices[VID-2].Id:=VID-1;M.Vertices[VID-2].P:=A1;M.Vertices[VID-1].Id:=VID;M.Vertices[VID-1].P:=B1;Inc(CID);SetLength(M.Curves,CID);M.Curves[CID-1].Id:=CID;M.Curves[CID-1].Kind:=gckLine;M.Curves[CID-1].P1:=A1;M.Curves[CID-1].P2:=V3(B1.X-A1.X,B1.Y-A1.Y,B1.Z-A1.Z);Inc(EID);SetLength(M.Edges,EID);M.Edges[EID-1].Id:=EID;M.Edges[EID-1].StartVertex:=VID-1;M.Edges[EID-1].EndVertex:=VID;M.Edges[EID-1].CurveId:=CID;M.Edges[EID-1].T0:=0;M.Edges[EID-1].T1:=1;M.Edges[EID-1].Sense:=1;end;
begin
 if ParamCount<1 then begin WriteLn(StdErr,'usage: iges2femgeo input.igs [output.fgeo]');Halt(2);end;
 FN:=ParamStr(1);M:=TFEMGeometryModel.Create;try M.SourceFormat:='IGES';M.SourceName:=ExtractFileName(FN);F:=TStringList.Create;try F.LoadFromFile(FN);I:=0;while I<F.Count do begin L:=F[I];if (Length(L)>=73) and (L[73]='P') then begin ParamText:=Trim(Copy(L,1,64));Seq:=Trim(Copy(L,65,8));Inc(I);while (I<F.Count) and (F[I][73]='P') and (Trim(Copy(F[I],65,8))=Seq) do begin ParamText:=ParamText+Trim(Copy(F[I],1,64));Inc(I);end;A:=CSV(ParamText);try if A.Count>0 then begin Typ:=StrToInt(Trim(A[0]));if Typ=110 then begin if A.Count>=7 then begin X1:=StrToFloat(Trim(A[1]));Y1:=StrToFloat(Trim(A[2]));Z1:=StrToFloat(Trim(A[3]));X2:=StrToFloat(Trim(A[4]));Y2:=StrToFloat(Trim(A[5]));Z2:=StrToFloat(Trim(A[6]));AddLine(V3(X1,Y1,Z1),V3(X2,Y2,Z2));end;end;end;except on E:Exception do WriteLn(StdErr,'WARNING GEO009 IGES parameter entity: ',E.Message);end;A.Free;end else Inc(I);end;finally F.Free;end;WriteLn(StdErr,'INFO IGES LINE entities mapped: ',EID);WriteLn(StdErr,'WARNING GEO009 IGES adaptor currently maps entity type 110 (LINE) only; unsupported entity types require explicit downstream handling.');if ParamCount>1 then begin if not SaveFGeoFile(ParamStr(2),M,Err) then begin WriteLn(StdErr,'ERROR ',Err);Halt(2);end;end else WriteFGeo(M,Output);finally M.Free;end;
end.
